apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/skupper-operator.openshift-operators: ''
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: skupper-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: skupper-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
#  startingCSV: skupper-operator.v1.4.1-rh-1
