apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - 00-skupper-subscription.yaml
  - 01-skupper-namespace.yaml
  - 02-skupper-site.yaml